services:
  manager_2492:
    # This pulls the image you pushed to Docker Hub
    image: nw2hd/manager-io:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: always
    
    # Resource management
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: ${MEMORY_LIMIT}
    
    # Network ports: Host Port -> Container Port
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:8080"
    
    # Data persistence
    volumes:
      - ${APP_PATH}/data:/data
    
    environment:
      - TZ=Asia/Kuala_Lumpur
    
    labels:
      createdBy: "bt_apps"
    
    networks:
      - baota_net

networks:
  baota_net:
    external: true
